# Generated by Django 3.1.12 on 2025-12-04 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('sleep', 'Sleep'), ('mental_health', 'Mental Health'), ('hydration', 'Hydration'), ('general', 'General')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-display_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('steps', 'Steps'), ('active_time', 'Active Time'), ('sleep', 'Sleep'), ('water', 'Water Intake'), ('calories', 'Calories'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'goal_type'],
                'unique_together': {('user', 'goal_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PreventiveCareReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('blood_test', 'Blood Test'), ('vaccination', 'Vaccination'), ('checkup', 'General Checkup'), ('screening', 'Health Screening'), ('dental', 'Dental Checkup'), ('eye_exam', 'Eye Examination'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('missed', 'Missed'), ('rescheduled', 'Rescheduled')], default='upcoming', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_interval', models.PositiveIntegerField(blank=True, help_text='Days between reminders', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyGoalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wellness.wellnessgoal')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
