# Generated by Django 3.1.12 on 2025-12-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailygoallog',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnessgoal',
            name='current_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnessgoal',
            name='target_value',
            field=models.FloatField(default=0),
        ),
    ]
