# Generated by Django 3.1.12 on 2025-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_auto_20251204_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessgoal',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
